server:
  port: 8180

spring:
 datasource:
   password: 1234
   username: root
   url: jdbc:mysql://localhost:3306/fornecedor?useTimezone=true&serverTimezone=UTC
 jpa:
   hibernate:
    ddl-auto: create